alert("Hola Mundo");
console.log("Hola");
console.log("Mundo");
console.log("Numeros");
[1,2,3,4].forEach(console.log);
console.log("2"/2);
let edad = prompt("¿Cuál es tu edad?",0);
alert('tienes '+ edad +' años');
let nombre = "Thomas";
console.log(`mi nombre es ${nombre}`);